--- 
title: "R for Psych Handbook"
author: "David John Baker"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "A handbook for psychologists at LSU to get started with R and Statistics."
---

# Preface

Welcome to the **R For Psychologists Handbook!**.
This book serves as a collection of resources used in the Department of Psychology at Louisiana State University (LSU) for the statistics classes required of all Graduate Student.
The book is **not** meant to serve as a comprehensive statistics textbook, for that please check out either [Explaining Psychological Statistics](https://www.wiley.com/en-us/Explaining+Psychological+Statistics%2C+4th+Edition-p-9781118436608) or Andy Field's [Discovering Statistics with R](https://us.sagepub.com/en-us/nam/discovering-statistics-using-r/book236067).
The book **is** meant to be a reference manual that gives a brief overview of a concept, then the code needed to run that analysis in R.

I try to add in references in each of the chapters in order for anyone to explore the concepts at length, but the material in this handbook should be enough to get any psychologist through the 4111 Intermediate Statistics and 7111 Multivariate Statistics courses.

The majority of the content comes from having taken and then TA'ed for both of these courses and collecting a lot of material on my own.
The content was generated by both Jason Hicks and Jason Harman, I just provided R as the glue to hold it all together.
The idea behind the book is that anyone going through the LSU stats rotation would be able to put in the extra work and learn R while they are doing the assignments in SPSS.

As noted in next chapter, it's hard to learn R, but worth doing it.
Personally found that R has opened up more opportunities than anything else I have invested in.
You don't need any programming experience to start and if you feel like you can't do this, know that reason I started R is I knew so little about computers during my Masters that my adviser had to show me how to do an ```IFELSE()```statement in Excel. 
At that point figured if I was going to learn, might as well be frustrated and get something good out of it.

One thing to learn a lot by running these examples, though the best way forward is to find your own dataset and start to set up project with it.

The book is still under construction and if you would like to help out with it, please get in touch!

Let's get cooking.
